---
deployment:
  tasks:
    - export DEPLOYPATH=/home/multiassetsbroke/public_html/
    - /bin/rsync -avz --delete --exclude='.git*' --exclude='.cpanel.yml' /home/multiassetsbroke/repositories/multiassetbrokers/ $DEPLOYPATH
